# Mini-project 1, Alexander Chase, 9/28/2021. 

top_line = '                                                            How does one stand on their own two feet?' 
middle_line = '                                                         What if their legs are broken?'
bottom_line= '                                                          We can explore some possible ideas together!'

top_line_two = '                                                        We could use prostetics..'
middle_line_two = '                                                     We could use crutches...'
bottom_line_two = '                                                     Or we could use a suspension system....'

top_line_three = '                                                      Why would we do this?'
middle_line_three = '                                                   What happened to us?'
bottom_line_three = '                                                   Where do we go now?'

top_line_four= '                                                        So we could walk again!'
middle_line_four= '                                                     Maybe we broke our legs falling'
bottom_line_four = '                                                    We go to the moon'

top_line_five = '                                                       What is broken, can be fixed'
middle_line_five = '                                                    With enough duct tape'
bottom_line_five = '                                                    Probably better to see a doctor'

'Use \n for new lines'


# Choose the one with highest length using the max function
# do help('max') in the python terminal to read this function's documentation
longest = max(len(top_line), len(middle_line), len(bottom_line))

# Define your border with this longest variable
border = '-'*longest



print(border + '-----------------------------------------------------------------')
print("\n")
print(top_line)
print("\n")
print(middle_line)
print("\n")
print(bottom_line)
input('Press Enter for next slide')
print(border + '-----------------------------------------------------------------')
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print(border + '-----------------------------------------------------------------')
print("\n")
print(top_line_two)
print("\n")
print(middle_line_two)
print("\n")
print(bottom_line_two)
print("\n")
input('Press Enter for next slide')
print(border + '-----------------------------------------------------------------')
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print(border + '-----------------------------------------------------------------')
print("\n")
print(top_line_three)
print("\n")
print(middle_line_three)
print("\n")
print(bottom_line_three)
input('Press Enter for next slide')
print(border + '-----------------------------------------------------------------')
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print(border + '-----------------------------------------------------------------')
print("\n")
print(top_line_four)
print("\n")
print(middle_line_four)
print("\n")
print(bottom_line_four)
print("\n")
input('Press Enter for next slide')
print(border + '-----------------------------------------------------------------')
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print("\n")
print(border + '-----------------------------------------------------------------')
print("\n")
print(top_line_five)
print("\n")
print(middle_line_five)
print("\n")
print(bottom_line_five)
print("\n")
input('Press Enter for an existential crisis')
print("\n")
print(border + '-----------------------------------------------------------------')


l = ['I love waffle house', 'hash browns', 'smothered in butter']
it = iter(l)
print(next(it))
print(next(it))
print(next(it))



